# Generated by Django 4.1.4 on 2023-02-17 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('carts', '0002_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-id',), 'verbose_name': 'Корзина товаров', 'verbose_name_plural': 'Корзины товаров'},
        ),
    ]
