# Generated by Django 4.1.5 on 2023-01-22 10:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('users_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None,
                                                                 verbose_name='Номер телефона'),
        ),
    ]
