# Generated by Django 4.1.5 on 2023-01-05 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_remove_product_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
