# Generated by Django 4.1.5 on 2023-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0012_alter_color_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_color',
            field=models.CharField(default='#ffffff', max_length=7, unique=True, verbose_name='Цвет в виде HEX'),
        ),
    ]
