# Generated by Django 4.1.5 on 2023-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('Новый заказ', 'Новый заказ'), ('В работе', 'В работе'), ('В доставке', 'В доставке'),
                         ('Выполнен', 'Выполнен')], default='Новый заказ', max_length=25, verbose_name='Статус заказа'),
        ),
    ]
