# Generated by Django 4.1.5 on 2023-02-23 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_alter_color_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('region', models.CharField(max_length=25, verbose_name='Регион')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('postal_code', models.PositiveSmallIntegerField(verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.address',
                                              verbose_name='Адрес доставки')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status',
                                             verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество продуктов')),
                ('unit_price', models.PositiveSmallIntegerField(verbose_name='Цена одного продукта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order',
                                            verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product',
                                              verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
