# Generated by Django 4.1.5 on 2023-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default='test.png', upload_to='products_images'),
        ),
    ]
