# Generated by Django 4.1.5 on 2023-01-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0008_alter_image_product_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Цвет')),
                ('hex_color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
